import sqlite3

con = sqlite3.connect("MyData.db")
cur = con.cursor()
query = """ CREATE TABLE IF NOT EXISTS data (
            X INTEGER PRIMARY KEY,
            IdEmpenho TEXT,
            Ano INTEGER,
            Vlr_AnulacaoEmpenho TEXT,
            CdFonteTCE INTEGER,
            CdFonteUG INTEGER,
            CNPJRaiz TEXT,
            CPFCNPJCredirQtNrs INTEGER,
            CPFCNPJCredor TEXT,
            Credor TEXT,
            DtEmpenho TEXT,
            DEFonteTCE TEXT,
            DEFonteUG TEXT,
            DEPrograma TEXT,
            DEProjAtiv TEXT,
            DtAnomes INTEGER,
            Elemento REAL,
            ElemDespesaTCE TEXT,
            ElemDespesaUG TEXT,
            Ente TEXT,
            Esfera TEXT,
            Funcao TEXT,
            Historico TEXT,
            IdContrato TEXT,
            IdFonte REAL,
            IdFuncao INTEGER,
            Id_Orgao REAL,
            IdPrograma INTEGER,
            IdSubFuncao INTEGER,
            IdUnid INTEGER,
            IdOrgao REAL,
            NrFonte INTEGER,
            NrFonteUG INTEGER,
            NrLicitacao TEXT,
            NrProjAtiv INTEGER,
            NrEmpenho INTEGER,
            ProgTrab TEXT,
            ProgTrabRed TEXT,
            ProjAtiv TEXT,
            SubFuncao TEXT,
            Tp_Empenho TEXT,
            Unidade TEXT,
            Vlr_Empenho TEXT,
            Vlr_Anul_Liquidacao TEXT,
            Vlr_Liquidacao TEXT,
            Vlr_Pagto TEXT,
            Vlr_Retencao TEXT,
            Vlr_SubEmpenho TEXT,
            Vlr_Empenhado TEXT,
            Vlr_Liquidado TEXT,
            Vlr_Pago TEXT
            ) """
cur.execute(query)
con.commit()
con.close()